[api_keys]
client_id = "43fefca2-a26b-415b-954d-ba9af37e3e1f"

[mapbox]
access_token = "pk.eyJ1IjoidG9yam9zc2FuZyIsImEiOiJjbTFsdjlwM2QwYWprMmxzOHZmcmZwbXdtIn0.eolOxs11aG331_RphwF1EQ"

[passwords]
"142" = "BrødTreBok"
"145" = "SkålBåtBok"
"149" = "RødBokSol"
"156" = "GrøtBokBil"
"158" = "KøTreHus"
"160" = "BrødVannBarn"
"162" = "GrøtHusHare"
"164" = "MølleBokLys"
"168" = "FjellBarnSol"
"169" = "BrødHundBil"
"173" = "RødLysVei"
"175" = "FjellBarnBok"
"177" = "SnøHusHund"
"179" = "FårTreBok"
"181" = "FårLysSol"
"183" = "GårVeiBarn"
"184" = "FjellVannBok"
"185" = "BlåHareBok"
"187" = "FjellBilHus"
"189" = "BrødBåtVei"
"191" = "LøkBåtHare"
"193" = "SkålHusBil"
"195" = "GrøtHusBil"
"197" = "GrøtBokHare"
"199" = "TU199"
"214" = "BrødBilTre"
"216" = "KøVindVei"
"218" = "KøVannHus"
"220" = "FårLysBok"
"222" = "KøHundBok"
"224" = "GårBarnVei"
"269" = "FårBilBok"
"273" = "MøteBarnHare"
"275" = "MøteVannVei"
"277" = "KøVeiBarn"
"279" = "LøkVindBarn"
"281" = "MølleLysSol"
"283" = "BlåHundVann"
"285" = "LøkSolVann"
"287" = "RødHareVei"
"289" = "GrøtHundHare"
"295" = "BrødHundSol"
"297" = "SkålBilVann"
"299" = "RødBarnVann"
"300" = "LøkTreBok"
"302" = "RødVindBil"
"304" = "SnøHusHund"
"305" = "MølleSolHus"
"306" = "MøteVannHund"
"307" = "MølleHundBil"
"1" = "SnøHundSol"
"5" = "BlåVannVind"
"7" = "BlåVannVei"
"9" = "SnøBilVann"
"13" = "BlåBokBil"
"14" = "FjellLysHund"
"16" = "FårHusBåt"
"18" = "GrøtBokVind"
"20" = "FårSolBarn"
"22" = "K22!"
"24" = "SnøTreVind"
"26" = "SkålHundHus"
"28" = "RødLysVann"
"30" = "KøLysSol"
"32" = "SkålVeiBok"
"34" = "BrødBåtVei"
"36" = "SkålTreHare"
"38" = "MølleVeiBåt"
"40" = "MøteBilVind"
"42" = "BrødBokBåt"
"44" = "KøBokHund"
"46" = "FårVannBarn"
"48" = "MølleHareSol"
"51" = "GrøtBarn"
"53" = "BrødHare"
"55" = "SkålHareBarn"
"57" = "FårLysVei"
"59" = "SkålVannHus"
"61" = "KøHareBil"
"63" = "GrøtHundBarn"
"65" = "GårHundLys"
"67" = "LøkTreBil"
"68" = "RødHundVei"
"69" = "SnøHareVei"
"999" = "FD999ø"
"1111" = "Snø9876"
"1112" = "Snøfokk457"
"1113" = "Sludd235"
"1114" = "Yr9786"
"1115" = "Snøfokk2536"
"3A" = "LøkBilBarn"
"3B" = "SnøBåtSol"
"3C" = "LøkSolBil"
"3D" = "MølleVeiHare"