[api_keys]
client_id = "43fefca2-a26b-415b-954d-ba9af37e3e1f"

[mapbox]
access_token = "pk.eyJ1IjoidG9yam9zc2FuZyIsImEiOiJjbTFsdjlwM2QwYWprMmxzOHZmcmZwbXdtIn0.eolOxs11aG331_RphwF1EQ"

[passwords]
"142" = "password_for_142"
"145" = "password_for_145"
"149" = "password_for_149"
"156" = "password_for_156"
"158" = "password_for_158"
"160" = "password_for_160"
"162" = "password_for_162"
"164" = "password_for_164"
"168" = "password_for_168"
"169" = "password_for_169"
"173" = "password_for_173"
"175" = "password_for_175"
"177" = "password_for_177"
"179" = "password_for_179"
"181" = "password_for_181"
"183" = "password_for_183"
"184" = "password_for_184"
"185" = "password_for_185"
"187" = "password_for_187"
"189" = "password_for_189"
"191" = "password_for_191"
"193" = "password_for_193"
"195" = "password_for_195"
"197" = "password_for_197"
"199" = "TU199"
"214" = "password_for_214"
"216" = "password_for_216"
"218" = "password_for_218"
"220" = "password_for_220"
"222" = "password_for_222"
"224" = "password_for_224"
"269" = "password_for_269"
"273" = "password_for_273"
"275" = "password_for_275"
"277" = "password_for_277"
"279" = "password_for_279"
"281" = "password_for_281"
"283" = "password_for_283"
"285" = "password_for_285"
"287" = "password_for_287"
"289" = "password_for_289"
"295" = "password_for_295"
"297" = "password_for_297"
"299" = "password_for_299"
"300" = "password_for_300"
"302" = "password_for_302"
"304" = "password_for_304"
"305" = "password_for_305"
"306" = "password_for_306"
"307" = "password_for_307"
"1" = "password_for_1"
"5" = "password_for_5"
"7" = "password_for_7"
"9" = "password_for_9"
"13" = "password_for_13"
"14" = "password_for_14"
"16" = "password_for_16"
"18" = "password_for_18"
"20" = "password_for_20"
"22" = "K22!"
"24" = "password_for_24"
"26" = "password_for_26"
"28" = "password_for_28"
"30" = "password_for_30"
"32" = "password_for_32"
"34" = "password_for_34"
"36" = "password_for_36"
"38" = "password_for_38"
"40" = "password_for_40"
"42" = "password_for_42"
"44" = "password_for_44"
"46" = "password_for_46"
"48" = "password_for_48"
"51" = "password_for_51"
"53" = "password_for_53"
"55" = "password_for_55"
"57" = "password_for_57"
"59" = "password_for_59"
"61" = "password_for_61"
"63" = "password_for_63"
"65" = "password_for_65"
"67" = "password_for_67"
"68" = "password_for_68"
"69" = "password_for_69"
"999" = "FD999"
"1111" = "Snø9876"
"1112" = "Snøfokk457"
"1113" = "Sludd235"
"1114" = "Yr9786"
"1115" = "Snøfokk2536"
"3A" = "password_for_3A"
"3B" = "password_for_3B"
"3C" = "password_for_3C"
"3D" = "password_for_3D"
